### ISSUE TITLE
Separate Static Data into Dedicated File

### ISSUE THREAD

**Issue by joystacktrek** [Thomasosho/AfriEdClone#1]
Static data is scattered throughout your application's codebase. This can make the codebase harder to manage, increase the chances of errors, and hinder the scalability and maintainability of our project. To improve our code organization and overall development process, we should consider separating static data into a dedicated file and folder as well.

Action Items:
- [x] #2

- [x] #3
https://github.com/Thomasosho/AfriEdClone/blob/2a22bb64053169eace9c111a60548cbd5c0ba46a/src/components/CocktailList.jsx#L7-L29

- [x] Update the import paths across the project wherever the static data was moved. This will ensure that the application still correctly accesses the data after the restructuring.

**Comment by joystacktrek** [comment]
@Thomasosho almost there :)

**Comment by Thomasosho** [comment]
@joystacktrek Thank You i will
