### ISSUE TITLE
Enhance Project with Required React Components

### ISSUE THREAD

**Issue by jdregalario-stacktrek** [Thomasosho/AfriEdClone#4]
Currently, your clone app is lacking the essential React components needed to fulfill the activity requirements. As per the guidelines, we are expected to have a minimum of 5 React components integrated into the project. 

**_Action Item:_**

- [x]  Create four more components in your clone app.

**Comment by jdregalario-stacktrek** [comment]
@Thomasosho

**Comment by Thomasosho** [comment]
> Currently, your clone app is lacking the essential React components needed to fulfill the activity requirements. As per the guidelines, we are expected to have a minimum of 5 React components integrated into the project.
> 
> **_Action Item:_**
> 
> * [ ]   Create four more components in your clone app.

Upon review of the issue, i created about seven(7) components. I'd need clarity on this please. i have two navigable screens and 7 components. I have a screenshot of where you can located those components
<img width="305" alt="Screen Shot 2023-09-01 at 2 19 55 PM" src="https://github.com/Thomasosho/AfriEdClone/assets/11132861/b9f42a7e-bb79-4d39-a063-9aa3558c8a99">

@jdregalario-stacktrek

**Comment by jdregalario-stacktrek** [comment]
This is noted @jdregalario-stacktrek, good job!
