### ISSUE TITLE
Implement Data Display Using JavaScript Array

### ISSUE THREAD

**Issue by jdregalario-stacktrek** [Thomasosho/AfriEdClone#5]
Your task is to implement data display functionality using JavaScript arrays in the project. This will help you understand how to structure data, import it into components, and render it in a user interface.

**_Action Item:_**

- [x]  Create Data Array:

In the src directory of the project, create a new JavaScript file named data.js. This file will serve as a source of data for your application. Inside data.js, define an array of objects. 

Example below: Each object should have properties like id, name, price, and any other relevant information. Here's an example of how the data.js file might look:
```js
   const products = [
     { id: 1, name: 'Product A', price: 19.99 },
     { id: 2, name: 'Product B', price: 29.99 },
     // Add more products as needed
   ];

   export default products;
```
   

- [x]  Use Array to Display Data:

Identify the appropriate component where you want to display the product data. This could be a component like ProductListComponent. Inside this component's file, import the products array from the data.js file you created earlier. You can use JavaScript's import statement for this purpose.

**Comment by jdregalario-stacktrek** [comment]
**Additional Guidelines:**

Make sure to follow best practices for JavaScript and React coding, including appropriate component organization and separation of concerns.
If you encounter any issues or have questions, feel free to ask for help by commenting on this issue.
This task is designed to help you grasp the concept of data management in a React application using JavaScript arrays.

**Comment by jdregalario-stacktrek** [comment]
@Thomasosho

**Comment by Thomasosho** [comment]
> Your task is to implement data display functionality using JavaScript arrays in the project. This will help you understand how to structure data, import it into components, and render it in a user interface.
> 
> **_Action Item:_**
> 
> * [ ]   Create Data Array:
> 
> In the src directory of the project, create a new JavaScript file named data.js. This file will serve as a source of data for your application. Inside data.js, define an array of objects.
> 
> Example below: Each object should have properties like id, name, price, and any other relevant information. Here's an example of how the data.js file might look:
> 
> ```js
>    const products = [
>      { id: 1, name: 'Product A', price: 19.99 },
>      { id: 2, name: 'Product B', price: 29.99 },
>      // Add more products as needed
>    ];
> 
>    export default products;
> ```
> 
> * [ ]   Use Array to Display Data:
> 
> Identify the appropriate component where you want to display the product data. This could be a component like ProductListComponent. Inside this component's file, import the products array from the data.js file you created earlier. You can use JavaScript's import statement for this purpose.

Okay, I will do that

**Comment by Thomasosho** [comment]
> Your task is to implement data display functionality using JavaScript arrays in the project. This will help you understand how to structure data, import it into components, and render it in a user interface.
> 
> **_Action Item:_**
> 
> * [x]   Create Data Array:
> 
> In the src directory of the project, create a new JavaScript file named data.js. This file will serve as a source of data for your application. Inside data.js, define an array of objects.
> 
> Example below: Each object should have properties like id, name, price, and any other relevant information. Here's an example of how the data.js file might look:
> 
> ```js
>    const products = [
>      { id: 1, name: 'Product A', price: 19.99 },
>      { id: 2, name: 'Product B', price: 29.99 },
>      // Add more products as needed
>    ];
> 
>    export default products;
> ```
> 
> * [x]   Use Array to Display Data:
> 
> Identify the appropriate component where you want to display the product data. This could be a component like ProductListComponent. Inside this component's file, import the products array from the data.js file you created earlier. You can use JavaScript's import statement for this purpose.

if you check the ```constant``` folder outside the src you'd see the data.js product array. That was what i imported. Now i could move it to the src folder, but from the issue i think you may have missed that. @jdregalario-stacktrek Please confirm the location you'd want me to place it.

**Comment by Thomasosho** [comment]
> > Your task is to implement data display functionality using JavaScript arrays in the project. This will help you understand how to structure data, import it into components, and render it in a user interface.
> > **_Action Item:_**
> > 
> > * [x]    Create Data Array:
> > 
> > In the src directory of the project, create a new JavaScript file named data.js. This file will serve as a source of data for your application. Inside data.js, define an array of objects.
> > Example below: Each object should have properties like id, name, price, and any other relevant information. Here's an example of how the data.js file might look:
> > ```js
> >    const products = [
> >      { id: 1, name: 'Product A', price: 19.99 },
> >      { id: 2, name: 'Product B', price: 29.99 },
> >      // Add more products as needed
> >    ];
> > 
> >    export default products;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * [x]    Use Array to Display Data:
> > 
> > Identify the appropriate component where you want to display the product data. This could be a component like ProductListComponent. Inside this component's file, import the products array from the data.js file you created earlier. You can use JavaScript's import statement for this purpose.
> 
> if you check the `constant` folder outside the src you'd see the data.js product array. That was what i imported. Now i could move it to the src folder, but from the issue i think you may have missed that. @jdregalario-stacktrek Please confirm the location you'd want me to place it.

This was done because of previous recommendation from my closed issue.

**Comment by Thomasosho** [comment]
<img width="301" alt="Screen Shot 2023-09-01 at 2 24 57 PM" src="https://github.com/Thomasosho/AfriEdClone/assets/11132861/e6dcb106-8a12-4d85-9b4d-c3d6017a5f3b">
<img width="803" alt="Screen Shot 2023-09-01 at 2 25 33 PM" src="https://github.com/Thomasosho/AfriEdClone/assets/11132861/703a5967-7f3b-487b-8ab1-ceff6d773418">
<img width="650" alt="Screen Shot 2023-09-01 at 2 26 01 PM" src="https://github.com/Thomasosho/AfriEdClone/assets/11132861/29efa4fd-76f7-48ad-883a-daa444732d3c">
@jdregalario-stacktrek find screenshots of my application.

**Comment by jdregalario-stacktrek** [comment]
This is noted @Thomasosho, thank you for the clarification!

**Comment by jdregalario-stacktrek** [comment]
Good Job!
